### PR TITLE
Merge 2.4

### PR DESCRIPTION
**Pull request by rodichenko**
# Description
Merging fixes (#45, #54, #55) for version 2.4 into version 2.5

# Check list

- [ ] Unit tests are provided
- [ ] Integration tests are provided (if CLI/API was changed)
- [ ] Documentation is updated

### CODE REVIEW

**Comment by vpolyakov88** [comment]
**BUG 1**
GTF/GFF3 files aren't loading by URL.
1. open NGB
2. click on point "FROM URL..."
3. select reference
4. insert link to file and index
(e.g. http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gtf.gz
http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gtf.gz.tbi
http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gff3.gz
http://ngb.opensource.epam.com/distr/data/genome/grch38/Homo_sapiens.GRCh38.gff3.gz.tbi)
5. go to any gene (e.g. 17: 31194990 - 31205517)
exp.: data is loaded
act.: 503 HTML code is returned

**Comment by vpolyakov88** [comment]
**BUG 2**
If user open VCF that haven't got index and then select VARIATION tab, file ID is displayed.
1. register VCF use --no_index option
2. add it to dataset
3. select this dataset
4. go to VARIATION tab
exp.: message that informed: {file_name} haven't index
act.: see screenshot
image

**Comment by vpolyakov88** [comment]
**BUG 3**
If on the VARIANTS tab is displaying many variations and user resize browser window all variations are disappeared.
1. open NGB
2. select big VCF or many VCFs
3. go to VARIANTS
4. resize window
exp.: all variations are re-rendered
act.: all variations are disappeared and they are appearing after scroll of table

**Comment by vpolyakov88** [comment]
**BUG 4**
Search by feature from BED doesn't work.
1. add annotation file to reference
2. open NGB
3. select dataset that use reference from step 1
4. try to search by feature from BED file
exp.: it works
act.: see screenshot
image

**Comment by vpolyakov88** [comment]
**BUG 5**
If user select second dataset and chromosome was selected tracks from second dataset isn't displayed.
1. open NGB
2. select dataset
3. choose chromosome
4. select another dataset
exp.: tracks from both datasets are displayed
act.: nothing changes

**Comment by mzueva** [comment]
@vpolyakov88 
BUG 1(Gene via URL) - I've reverted asyc dispatch for BAM & Gene track since they already heavily use async execution, I'll open a new issue to handle this case. For now Gene track works correctly for registered files/ via URL without any timeout
BUG 4(search by BED features) - fixed
Also I fixed bug with showing annotation gene file in dataset tree (annotation files shouldn't be shown in dataset structure)

**Comment by vpolyakov88** [comment]
**BUG 6**
SV isn't displayed in variation menu.
1. select VCF (gene should be added to reference)
2. go to VARIANTS tab
3. click on info icon near SV
exp.: SV is rendered
act.: error message "Error loading variant info"

**Comment by mzueva** [comment]
@vpolyakov88 
I've pushed a fix for BUG 2 (file name in the error message)

**Comment by vpolyakov88** [comment]
**BUG 6**
Unhandled exception in gene info
1. select dataset that have indexed GTF/GFF3
2. find OR6K1P gene
3. click gene and click "Show info" point in appeared menu
4. go to "UNIPROT" tab
exp.: handlen and userfriendly error message
act.: see screenshot
image

**Pull request merged**
