### PR TITLE
Client visual tests

### PR DESCRIPTION
**Pull request by lifeart**
# Description

adds client visual regression testing for svg's, canvas and such

## Background

figure out way to catch possible regressions in plots

## Changes

* client-tests folder created with basic test logic
* node_modules added to .gitignore
* github actions pipeline added to execute tests

## Acceptance criteria

github pipeline after proper endpoint aligments should be green

# Check list

- [+] Unit tests are provided
- [+] Integration tests are provided (if CLI/API was changed)
- [+] Documentation is updated

### CODE REVIEW

**Comment by rodichenko** [comment]
Hi, @lifeart !
Thank you for the contribution, we really appreciate your work!
Unfortunately, I was not able to run tests on my environment:
* macOS Catalina (10.15.7)
* node (14.6.0)
* npm (6.14.8)
* yarn (installed globally, 1.22.10).

There are several scenarios which lead to the different errors:

**Pure `yarn ci` call**
* I ran `yarn` command at `client-tests` directory
* I ran `yarn ci` command
That leads to the `cannot find module 'webpack'` error:
```bash
> yarn --cwd ./../client serve:test

$ node webpack.devserver.js --env test
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'webpack'
```

I ran `npm install` command at the `client` directory and tried again:

**`yarn ci` call after installing client packages**
* I ran `year` command at `client-tests` directory
* I ran `npm install` command at `client` directory
* I ran `yarn ci` command
That leads to the `cannot read property 'screenshot' of null` error for all tests:
```bash
    TypeError: Cannot read property 'screenshot' of null

      76 |     await page.waitForTimeout(10000);
      77 |     const element = await page.$(`.tracks-panel`);
    > 78 |     const screenshot = await element.screenshot({ omitBackground: true });
         |                                      ^
      79 |     expect(screenshot).toMatchSnapshot(`barchart-panel.png`, { threshold: 0 });
      80 |   });
      81 |

```
@lifeart any ideas what is causing an error?

Also, I have some questions TBD:
* Do we really need `yarn` here? We already use `npm` for our client, can we also use it for tests?
* Can we move all tests scripts into `client` directory? I think, it's more comfortable to have all scripts (serve, build, test, lint) at the single place.
At my opinion, we won't face mentioned issues if we have all scripts together at `client` folder, because we'll definitely run `npm install` before any script execution.

**Comment by lifeart** [comment]
@rodichenko `Cannot read property 'screenshot' of null` may happen if you have different backend setted up (api may return not-found for gene or such) (ensure VPN is enabled for default endpoint for test setup)

Other comments adressed, folders moved, readme updated

**Comment by OlegTar** [comment]
@lifeart why do you use folio instead of Protractor which is built by AngularJS team?

**Comment by lifeart** [comment]
@OlegTar folio framework agnostic and plays well with playwright (officially supported), there is no angular deps or bindings in test, so we don't need angular libs here.

**Pull request merged**
